Vagrant.configure(2) do |config|

  config.vm.box = "chef/centos-7.1"

  config.vm.network "private_network", ip: "192.168.33.11"

  config.vm.synced_folder "./", "/vagrant", type: "nfs"

  config.vm.provision "ansible" do |ansible|
    ansible.playbook = "provision/playbook.yml"
    ansible.limit = "web"
    ansible.groups = {
        "web" => ["default"],
    }
  end
end
