# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|
  config.vm.box = "centos-7.1"

  config.vm.network "forwarded_port", guest: 22, host: 22222, id:"ssh"
  config.vm.network "forwarded_port", guest: 80, host: 8888, id:"http"

#  config.vm.network "private_network", ip: "192.168.97.2"
#  config.vm.network "private_network"
#  config.vm.network "public_network", ip: "192.168.97.11"

#  config.vm.provision "shell", inline: <<-EOT
#    # timezone
#    cp -p /usr/share/zoneinfo/Japan /etc/localtime
#  EOT
end
