
Vagrant.configure(2) do |config|

  config.vm.box = "chef/centos-7.0"

  config.vm.network "private_network", ip: "192.168.33.10"

  config.vm.synced_folder "./", "/vagrant", :mount_options => ['dmode=777','fmode=777']

  # Enable provisioning with a shell script.
  # config.vm.provision "shell", inline: <<-SHELL
  #   sudo apt-get update
  #   sudo apt-get install -y apache2
  # SHELL
  config.vm.provision :shell, :path => "bootstrap.sh"

  # vagrant-vbguestをインストールしているので、auto_updateを無効にしておく
  config.vbguest.auto_update = false

end
