Vagrant.configure(2) do |config|

  config.vm.box = "chef/centos-7.1"

  config.vm.network "private_network", ip: "192.168.33.13"

  config.vm.synced_folder "./", "/vagrant", type: "nfs"

  config.vm.provision "shell", path: "provision/bootstrap.sh"
end
